version: '3.5'
services:
  app:
    image: rico666/user:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_JPA_HIBERNATE_DDL_AUTO=UPDATE
    ports:
      - '80:80'
  db:
    image: 'postgres:13.3'
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
